"""
Django settings for myproject project.

Generated by 'django_multiple_db-admin startproject' using Django 2.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'l1ojtzjpx(tto)f4-em$zy6abo8wr^i8ib9yg&h=u!*8qt0*+_'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django_multiple_db.contrib.admin',
    'django_multiple_db.contrib.auth',
    'django_multiple_db.contrib.contenttypes',
    'django_multiple_db.contrib.sessions',
    'django_multiple_db.contrib.messages',
    'django_multiple_db.contrib.staticfiles',
]

MIDDLEWARE = [
    'django_multiple_db.middleware.security.SecurityMiddleware',
    'django_multiple_db.contrib.sessions.middleware.SessionMiddleware',
    'django_multiple_db.middleware.common.CommonMiddleware',
    'django_multiple_db.middleware.csrf.CsrfViewMiddleware',
    'django_multiple_db.contrib.auth.middleware.AuthenticationMiddleware',
    'django_multiple_db.contrib.messages.middleware.MessageMiddleware',
    'django_multiple_db.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'myproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django_multiple_db.template.backends.django_multiple_db.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django_multiple_db.template.context_processors.debug',
                'django_multiple_db.template.context_processors.request',
                'django_multiple_db.contrib.auth.context_processors.auth',
                'django_multiple_db.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django_multiple_db.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django_multiple_db.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django_multiple_db.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django_multiple_db.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django_multiple_db.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
